version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: muchiri
      POSTGRES_DB: cipherealm
  app:
    image: cipherealm
    ports:
      - 13000:3000

# services:
#   db:
#     image: postgres
#     container_name: cipherealm
#     environment:
#       POSTGRES_USER: muchiri
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     restart: always