import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'sonner';
import "./globals.css";
import { ThemeProvider } from "@/components/themes/theme-provider";
import UserProvider from "@/providers/user-provider";
import SiteShell from "@/components/shells/site-shell";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UserProvider>
              <SiteShell>
                {children}
              </SiteShell>
            </UserProvider>
            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
  );
}
